import './globals.css';
import React, { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen bg-gray-100">
          <header className="bg-white shadow">
            <div className="container mx-auto py-4 px-8 flex justify-between items-center">
              <div className="text-2xl font-semibold">
                <Link href="/">Rathawut.com</Link>
              </div>
              <nav className="space-x-4">
                <Link href="/">Home</Link>
                <Link href="/about">About Me</Link>
              </nav>
            </div>
          </header>
          <main className="container mx-auto flex-grow py-8 px-4">
            {children}
          </main>
          <footer className="bg-gray-200 py-4 px-8 text-center">
            &copy; {new Date().getFullYear()} Rathawut.com All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
